Spaces to tabs

diff --git a/lib/ynh_lxd_package_check b/lib/ynh_lxd_package_check
--- a/lib/ynh_lxd_package_check
+++ b/lib/ynh_lxd_package_check
@@ -5,138 +5,138 @@
 #=================================================
 
 LXC_CREATE () {
-    log_info "Launching new LXC $LXC_NAME ..."
-    # Check if we can launch container from YunoHost remote image
-    if lxc remote list | grep -q "yunohost" && lxc image list yunohost:$LXC_BASE | grep -q -w $LXC_BASE; then
-        lxc launch yunohost:$LXC_BASE $LXC_NAME \
-            -c security.nesting=true \
-            -c security.privileged=true \
-            -c limits.memory=80% \
-            -c limits.cpu.allowance=80% \
-            >>/proc/self/fd/3
-    # Check if we can launch container from a local image
-    elif lxc image list $LXC_BASE | grep -q -w $LXC_BASE; then
-        lxc launch $LXC_BASE $LXC_NAME \
-            -c security.nesting=true \
-            -c security.privileged=true \
-            -c limits.memory=80% \
-            -c limits.cpu.allowance=80% \
-            >>/proc/self/fd/3
-    else
-        log_critical "Can't find base image $LXC_BASE, run ./package_check.sh --rebuild"
-    fi
-    
-    pipestatus="${PIPESTATUS[0]}"
-    location=$(lxc list --format json | jq -e --arg LXC_NAME $LXC_NAME '.[] | select(.name==$LXC_NAME) | .location' | tr -d '"')
-    [[ "$location" != "none" ]] && log_info "... on $location"
+	log_info "Launching new LXC $LXC_NAME ..."
+	# Check if we can launch container from YunoHost remote image
+	if lxc remote list | grep -q "yunohost" && lxc image list yunohost:$LXC_BASE | grep -q -w $LXC_BASE; then
+		lxc launch yunohost:$LXC_BASE $LXC_NAME \
+			-c security.nesting=true \
+			-c security.privileged=true \
+			-c limits.memory=80% \
+			-c limits.cpu.allowance=80% \
+			>>/proc/self/fd/3
+	# Check if we can launch container from a local image
+	elif lxc image list $LXC_BASE | grep -q -w $LXC_BASE; then
+		lxc launch $LXC_BASE $LXC_NAME \
+			-c security.nesting=true \
+			-c security.privileged=true \
+			-c limits.memory=80% \
+			-c limits.cpu.allowance=80% \
+			>>/proc/self/fd/3
+	else
+		log_critical "Can't find base image $LXC_BASE, run ./package_check.sh --rebuild"
+	fi
+	
+	pipestatus="${PIPESTATUS[0]}"
+	location=$(lxc list --format json | jq -e --arg LXC_NAME $LXC_NAME '.[] | select(.name==$LXC_NAME) | .location' | tr -d '"')
+	[[ "$location" != "none" ]] && log_info "... on $location"
 
-    [[ "$pipestatus" -eq 0 ]] || exit 1
+	[[ "$pipestatus" -eq 0 ]] || exit 1
 
-    _LXC_START_AND_WAIT $LXC_NAME
-    set_witness_files
-    lxc snapshot $LXC_NAME snap0
+	_LXC_START_AND_WAIT $LXC_NAME
+	set_witness_files
+	lxc snapshot $LXC_NAME snap0
 }
 
 LXC_SNAPSHOT_EXISTS() {
-    local snapname=$1
-    lxc list --format json \
-        | jq -e --arg LXC_NAME $LXC_NAME --arg snapname $snapname \
-        '.[] | select(.name==$LXC_NAME) | .snapshots[] | select(.name==$snapname)' \
-            >/dev/null
+	local snapname=$1
+	lxc list --format json \
+		| jq -e --arg LXC_NAME $LXC_NAME --arg snapname $snapname \
+		'.[] | select(.name==$LXC_NAME) | .snapshots[] | select(.name==$snapname)' \
+			>/dev/null
 }
 
 CREATE_LXC_SNAPSHOT () {
-    # Create a temporary snapshot
+	# Create a temporary snapshot
 
-    local snapname=$1
+	local snapname=$1
 
-    start_timer
+	start_timer
 
-    # Check all the witness files, to verify if them still here
-    check_witness_files >&2
+	# Check all the witness files, to verify if them still here
+	check_witness_files >&2
 
-    # Remove swap files to avoid killing the CI with huge snapshots.
-    CLEAN_SWAPFILES
-    
-    LXC_STOP $LXC_NAME
+	# Remove swap files to avoid killing the CI with huge snapshots.
+	CLEAN_SWAPFILES
+	
+	LXC_STOP $LXC_NAME
 
-    # Check if the snapshot already exist
-    if ! LXC_SNAPSHOT_EXISTS "$snapname"
-    then
-        log_info "(Creating snapshot $snapname ...)"
-        lxc snapshot $LXC_NAME $snapname
-    fi
+	# Check if the snapshot already exist
+	if ! LXC_SNAPSHOT_EXISTS "$snapname"
+	then
+		log_info "(Creating snapshot $snapname ...)"
+		lxc snapshot $LXC_NAME $snapname
+	fi
 
-    _LXC_START_AND_WAIT $LXC_NAME
+	_LXC_START_AND_WAIT $LXC_NAME
 
-    stop_timer 1
+	stop_timer 1
 }
 
 LOAD_LXC_SNAPSHOT () {
-    local snapname=$1
-    log_debug "Loading snapshot $snapname ..."
+	local snapname=$1
+	log_debug "Loading snapshot $snapname ..."
 
-    # Remove swap files before restoring the snapshot.
-    CLEAN_SWAPFILES
+	# Remove swap files before restoring the snapshot.
+	CLEAN_SWAPFILES
 
-    LXC_STOP $LXC_NAME
+	LXC_STOP $LXC_NAME
 
-    lxc restore $LXC_NAME $snapname
-    lxc start $LXC_NAME
-    _LXC_START_AND_WAIT $LXC_NAME
+	lxc restore $LXC_NAME $snapname
+	lxc start $LXC_NAME
+	_LXC_START_AND_WAIT $LXC_NAME
 }
 
 #=================================================
 
 LXC_EXEC () {
-    # Start the lxc container and execute the given command in it
-    local cmd=$1
+	# Start the lxc container and execute the given command in it
+	local cmd=$1
 
-    _LXC_START_AND_WAIT $LXC_NAME
+	_LXC_START_AND_WAIT $LXC_NAME
 
-    start_timer
+	start_timer
 
-    # Execute the command given in argument in the container and log its results.
-    lxc exec $LXC_NAME --env PACKAGE_CHECK_EXEC=1 -t -- /bin/bash -c "$cmd" | tee -a "$complete_log" $current_test_log
+	# Execute the command given in argument in the container and log its results.
+	lxc exec $LXC_NAME --env PACKAGE_CHECK_EXEC=1 -t -- /bin/bash -c "$cmd" | tee -a "$complete_log" $current_test_log
 
-    # Store the return code of the command
-    local returncode=${PIPESTATUS[0]}
+	# Store the return code of the command
+	local returncode=${PIPESTATUS[0]}
 
-    log_debug "Return code: $returncode"
+	log_debug "Return code: $returncode"
 
-    stop_timer 1
-    # Return the exit code of the ssh command
-    return $returncode
+	stop_timer 1
+	# Return the exit code of the ssh command
+	return $returncode
 }
 
 LXC_STOP () {
-    local container_to_stop=$1
-    # (We also use timeout 30 in front of the command because sometime lxc
-    # commands can hang forever despite the --timeout >_>...)
-    timeout 30 lxc stop --timeout 15 $container_to_stop 2>/dev/null
+	local container_to_stop=$1
+	# (We also use timeout 30 in front of the command because sometime lxc
+	# commands can hang forever despite the --timeout >_>...)
+	timeout 30 lxc stop --timeout 15 $container_to_stop 2>/dev/null
 
-    # If the command times out, then add the option --force
-    if [ $? -eq 124 ]; then
-        timeout 30 lxc stop --timeout 15 $container_to_stop --force 2>/dev/null
-    fi
+	# If the command times out, then add the option --force
+	if [ $? -eq 124 ]; then
+		timeout 30 lxc stop --timeout 15 $container_to_stop --force 2>/dev/null
+	fi
 
 }
 
 LXC_RESET () {
-    # If the container exists
-    if lxc info $LXC_NAME >/dev/null 2>/dev/null; then
-        # Remove swap files before deletting the continer
-        CLEAN_SWAPFILES
-    fi 
+	# If the container exists
+	if lxc info $LXC_NAME >/dev/null 2>/dev/null; then
+		# Remove swap files before deletting the continer
+		CLEAN_SWAPFILES
+	fi 
 
-    LXC_STOP $LXC_NAME
+	LXC_STOP $LXC_NAME
 
-    if lxc info $LXC_NAME >/dev/null 2>/dev/null; then
-        local current_storage=$(lxc list $LXC_NAME --format json --columns b | jq '.[].expanded_devices.root.pool')
-        swapoff "$(lxc storage get $current_storage source)/containers/$LXC_NAME/rootfs/swap" 2>/dev/null
-    fi 
+	if lxc info $LXC_NAME >/dev/null 2>/dev/null; then
+		local current_storage=$(lxc list $LXC_NAME --format json --columns b | jq '.[].expanded_devices.root.pool')
+		swapoff "$(lxc storage get $current_storage source)/containers/$LXC_NAME/rootfs/swap" 2>/dev/null
+	fi 
 
-    lxc delete $LXC_NAME --force 2>/dev/null
+	lxc delete $LXC_NAME --force 2>/dev/null
 }
 
 
@@ -144,7 +144,7 @@ _LXC_START_AND_WAIT() {
 
 	restart_container()
 	{
-        LXC_STOP $1
+		LXC_STOP $1
 		lxc start "$1"
 	}
 
@@ -198,115 +198,115 @@ _LXC_START_AND_WAIT() {
 		# Fail if the container failed to start
 		if [ $i -eq $max_try ] && [ $failstart -eq 1 ]
 		then
-            log_error "The container miserably failed to start or to connect to the internet"
-            lxc info --show-log $1
+			log_error "The container miserably failed to start or to connect to the internet"
+			lxc info --show-log $1
 			return 1
 		fi
 	done
 
-    LXC_IP=$(lxc exec $1 -- hostname -I | cut -d' ' -f1 | grep -E -o "\<[0-9.]{8,}\>")
+	LXC_IP=$(lxc exec $1 -- hostname -I | cut -d' ' -f1 | grep -E -o "\<[0-9.]{8,}\>")
 }
 
 CLEAN_SWAPFILES() {
-    # Restart it if needed
-    if [ "$(lxc info $LXC_NAME | grep Status | awk '{print tolower($2)}')" != "running" ]; then
-        lxc start $LXC_NAME
-        _LXC_START_AND_WAIT $LXC_NAME
-    fi
-    lxc exec $LXC_NAME -- bash -c 'for swapfile in $(ls /swap_* 2>/dev/null); do swapoff $swapfile; done'
-    lxc exec $LXC_NAME -- bash -c 'for swapfile in $(ls /swap_* 2>/dev/null); do rm -f $swapfile; done'
+	# Restart it if needed
+	if [ "$(lxc info $LXC_NAME | grep Status | awk '{print tolower($2)}')" != "running" ]; then
+		lxc start $LXC_NAME
+		_LXC_START_AND_WAIT $LXC_NAME
+	fi
+	lxc exec $LXC_NAME -- bash -c 'for swapfile in $(ls /swap_* 2>/dev/null); do swapoff $swapfile; done'
+	lxc exec $LXC_NAME -- bash -c 'for swapfile in $(ls /swap_* 2>/dev/null); do rm -f $swapfile; done'
 }
 
 RUN_INSIDE_LXC() {
-    lxc exec $LXC_NAME -- "$@"
+	lxc exec $LXC_NAME -- "$@"
 }
 
 set_witness_files () {
-    # Create files to check if the remove script does not remove them accidentally
-    log_debug "Create witness files..."
+	# Create files to check if the remove script does not remove them accidentally
+	log_debug "Create witness files..."
 
-    create_witness_file () {
-        [ "$2" = "file" ] && local action="touch" || local action="mkdir -p"
-        RUN_INSIDE_LXC $action $1
-    }
+	create_witness_file () {
+		[ "$2" = "file" ] && local action="touch" || local action="mkdir -p"
+		RUN_INSIDE_LXC $action $1
+	}
 
-    # Nginx conf
-    create_witness_file "/etc/nginx/conf.d/$DOMAIN.d/witnessfile.conf" file
-    create_witness_file "/etc/nginx/conf.d/$SUBDOMAIN.d/witnessfile.conf" file
+	# Nginx conf
+	create_witness_file "/etc/nginx/conf.d/$DOMAIN.d/witnessfile.conf" file
+	create_witness_file "/etc/nginx/conf.d/$SUBDOMAIN.d/witnessfile.conf" file
 
-    # /etc
-    create_witness_file "/etc/witnessfile" file
+	# /etc
+	create_witness_file "/etc/witnessfile" file
 
-    # /opt directory
-    create_witness_file "/opt/witnessdir" directory
+	# /opt directory
+	create_witness_file "/opt/witnessdir" directory
 
-    # /var/www directory
-    create_witness_file "/var/www/witnessdir" directory
+	# /var/www directory
+	create_witness_file "/var/www/witnessdir" directory
 
-    # /home/yunohost.app/
-    create_witness_file "/home/yunohost.app/witnessdir" directory
+	# /home/yunohost.app/
+	create_witness_file "/home/yunohost.app/witnessdir" directory
 
-    # /var/log
-    create_witness_file "/var/log/witnessfile" file
+	# /var/log
+	create_witness_file "/var/log/witnessfile" file
 
-    # Config fpm
-    create_witness_file "/etc/php/$DEFAULT_PHP_VERSION/fpm/pool.d/witnessfile.conf" file
+	# Config fpm
+	create_witness_file "/etc/php/$DEFAULT_PHP_VERSION/fpm/pool.d/witnessfile.conf" file
 
-    # Config logrotate
-    create_witness_file "/etc/logrotate.d/witnessfile" file
+	# Config logrotate
+	create_witness_file "/etc/logrotate.d/witnessfile" file
 
-    # Config systemd
-    create_witness_file "/etc/systemd/system/witnessfile.service" file
+	# Config systemd
+	create_witness_file "/etc/systemd/system/witnessfile.service" file
 
-    # Database
-    RUN_INSIDE_LXC mysqladmin --wait status > /dev/null 2>&1
-    echo "CREATE DATABASE witnessdb" | RUN_INSIDE_LXC mysql --wait > /dev/null 2>&1
+	# Database
+	RUN_INSIDE_LXC mysqladmin --wait status > /dev/null 2>&1
+	echo "CREATE DATABASE witnessdb" | RUN_INSIDE_LXC mysql --wait > /dev/null 2>&1
 }
 
 check_witness_files () {
-    # Check all the witness files, to verify if them still here
+	# Check all the witness files, to verify if them still here
 
-    check_file_exist () {
-        if RUN_INSIDE_LXC test ! -e "$1"
-        then
-            log_error "The file $1 is missing ! Something gone wrong !"
-            SET_RESULT "failure" witness
-        fi
-    }
+	check_file_exist () {
+		if RUN_INSIDE_LXC test ! -e "$1"
+		then
+			log_error "The file $1 is missing ! Something gone wrong !"
+			SET_RESULT "failure" witness
+		fi
+	}
 
-    # Nginx conf
-    check_file_exist "/etc/nginx/conf.d/$DOMAIN.d/witnessfile.conf"
-    check_file_exist "/etc/nginx/conf.d/$SUBDOMAIN.d/witnessfile.conf"
+	# Nginx conf
+	check_file_exist "/etc/nginx/conf.d/$DOMAIN.d/witnessfile.conf"
+	check_file_exist "/etc/nginx/conf.d/$SUBDOMAIN.d/witnessfile.conf"
 
-    # /etc
-    check_file_exist "/etc/witnessfile"
+	# /etc
+	check_file_exist "/etc/witnessfile"
 
-    # /opt directory
-    check_file_exist "/opt/witnessdir"
+	# /opt directory
+	check_file_exist "/opt/witnessdir"
 
-    # /var/www directory
-    check_file_exist "/var/www/witnessdir"
+	# /var/www directory
+	check_file_exist "/var/www/witnessdir"
 
-    # /home/yunohost.app/
-    check_file_exist "/home/yunohost.app/witnessdir"
+	# /home/yunohost.app/
+	check_file_exist "/home/yunohost.app/witnessdir"
 
-    # /var/log
-    check_file_exist "/var/log/witnessfile"
+	# /var/log
+	check_file_exist "/var/log/witnessfile"
 
-    # Config fpm
-    check_file_exist "/etc/php/$DEFAULT_PHP_VERSION/fpm/pool.d/witnessfile.conf"
+	# Config fpm
+	check_file_exist "/etc/php/$DEFAULT_PHP_VERSION/fpm/pool.d/witnessfile.conf"
 
-    # Config logrotate
-    check_file_exist "/etc/logrotate.d/witnessfile"
+	# Config logrotate
+	check_file_exist "/etc/logrotate.d/witnessfile"
 
-    # Config systemd
-    check_file_exist "/etc/systemd/system/witnessfile.service"
+	# Config systemd
+	check_file_exist "/etc/systemd/system/witnessfile.service"
 
-    # Database
-    if ! RUN_INSIDE_LXC mysqlshow witnessdb > /dev/null 2>&1
-    then
-        log_error "The database witnessdb is missing ! Something gone wrong !"
-        SET_RESULT "failure" witness
-        return 1
-    fi
+	# Database
+	if ! RUN_INSIDE_LXC mysqlshow witnessdb > /dev/null 2>&1
+	then
+		log_error "The database witnessdb is missing ! Something gone wrong !"
+		SET_RESULT "failure" witness
+		return 1
+	fi
 }
